### ISSUE TITLE
Got a new release?

### ISSUE THREAD

**Issue by kpishere** [sintech/kicad-macos#1]
There is something wrong with the file on download from your latest release?  It is always failing for me on download.

**Comment by sintech** [comment]
What do you mean by failing?
Regarding new versions, I will try to build latest 8.0.4, but can't guarantee it'll work fine.

**Comment by kpishere** [comment]
Thanks very much! I've been attempting to do it but man, it is big.  Kind of a rabbit hole for me right now too. 

As for downloading the 7.07 version you've got there ... I dunno, over 5 times now, it downloads until the last few bytes and then fails in Floorp browser.  Never seen that before with github, other sources are fine.  I'll try with wget or something.

**Comment by kpishere** [comment]
It seems to be a github issue, like the token expires and client is in midst of download and does not renew and continue correctly.   

Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/643166711/7d8a6e98-4333-44dc-a19c-bbb53b18c646?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240909%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240909T002243Z&X-Amz-Expires=300&X-Amz-Signature=694ba45d3367e0d724ba8dfdf0c4ca3f1b47fd2609757d3a7bd97832ca87f6f0&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=643166711&response-content-disposition=attachment%3B%20filename%3Dkicad-unified-macos-7.0.7.dmg&response-content-type=application%2Foctet-stream [following]
--2024-09-08 20:22:43--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/643166711/7d8a6e98-4333-44dc-a19c-bbb53b18c646?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240909%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240909T002243Z&X-Amz-Expires=300&X-Amz-Signature=694ba45d3367e0d724ba8dfdf0c4ca3f1b47fd2609757d3a7bd97832ca87f6f0&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=643166711&response-content-disposition=attachment%3B%20filename%3Dkicad-unified-macos-7.0.7.dmg&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1247445757 (1.2G) [application/octet-stream]
Saving to: ‘kicad-unified-macos-7.0.7.dmg.2’

kicad-unified-macos-7.0.7.dmg.2          66%[===================================================>                           ] 790.00M  2.25MB/s    in 6m 17s  

2024-09-08 20:29:00 (2.10 MB/s) - Connection closed at byte 828375040. Retrying.

--2024-09-08 20:29:01--  (try: 2)  https://objects.githubusercontent.com/github-production-release-asset-2e65be/643166711/7d8a6e98-4333-44dc-a19c-bbb53b18c646?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240909%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240909T002243Z&X-Amz-Expires=300&X-Amz-Signature=694ba45d3367e0d724ba8dfdf0c4ca3f1b47fd2609757d3a7bd97832ca87f6f0&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=643166711&response-content-disposition=attachment%3B%20filename%3Dkicad-unified-macos-7.0.7.dmg&response-content-type=application%2Foctet-stream
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
--2024-09-08 20:29:01--  http://kicad-unified-macos-7.0.7.alt.dmg/
Resolving kicad-unified-macos-7.0.7.alt.dmg (kicad-unified-macos-7.0.7.alt.dmg)... failed: nodename nor servname provided, or not known.
wget: unable to resolve host address ‘kicad-unified-macos-7.0.7.alt.dmg’
Mac-mini:Download kevinpeck$

**Comment by kpishere** [comment]
Ok, Safari as a web client managed the download well.  Can try 7.0.7 now and fingers crossed, loads the project I wanna make a gerber file with.

**Comment by sintech** [comment]
Just finished building 8.0.5. 
It works fine on my test Catalina Macbook.
Posted new release.

**Comment by kpishere** [comment]
Oh that is fantastic!  Thank you very much!  Also, it works just fine.  PS: I just refuse to upgrade any more with Apple.  Catalina is such a pain in many ways but was still able to disable much of the creep-ware in it.
